### ISSUE TITLE
MFTECmd version 1.2.2.1  

### ISSUE THREAD

**Issue by 0CM** [EZToolsManuals/EZToolsManuals#56]

**Comment by EricZimmerman** [comment]
Closed. No details.

**Comment by 0CM** [comment]
MFTECmd version 1.2.2.1  | .NET Desktop Runtime 6.0.28

E01 image with partition that got unallocated space wiped by "SDELETE -z".
Image itself works fine, tools like FTK Imager, BlackLight sees allocated space fine.

Parsing failing with the following error:

There was an error loading the file! Error: Offset and length were out of bounds for the array or count is greater than the number of elements from index to the end of the source collection.
System.ArgumentException: Offset and length were out of bounds for the array or count is greater than the number of elements from index to the end of the source collection.
   at System.Buffer.BlockCopy(Array src, Int32 srcOffset, Array dst, Int32 dstOffset, Int32 count)
   at MFT.Attributes.AttributeList..ctor(Byte[] rawBytes)
   at MFT.FileRecord..ctor(Byte[] rawBytes, Int32 offset, Boolean recoverFromSlack)
   at MFT.Mft..ctor(Stream fileStream, Boolean recoverFromSlack)
   at MFT.MftFile.Load(String mftPath, Boolean recoverFromSlack)
   at MFTECmd.Program.ProcessMft(String file, Boolean vss, Boolean dedupe, String body, String bdl, String bodyf, Boolean blf, String csv, String csvf, String json, String jsonf, Boolean fl, String dt, String dd, String do, Boolean fls, Boolean includeShort, Boolean alltimestamp, String de, Boolean rs, String drDir)

**Comment by 0CM** [comment]
Hi Eric,

the E01 has valid NTFS partition with files, but as part of the disk sanitisation and image size reduction the unallocated space of the disk was wiped (zeroed), before imaging.  

Parsing (with MFTECmd)of MFT exported before the sdelete, work just fine 

sdelete -z  (Zero free space (good for virtual disk optimization) was used on the drive to reduce the size of the final image. 
https://learn.microsoft.com/en-us/sysinternals/downloads/sdelete

Parsing (with MFTECmd) MFT exported from the drive after the zeroing (free space only) is failing with the provided error.   
Other tools works fine, FTK imager and other tools loads the image its content without issues. Thus I can only assume the MFT is not corrupted. 

CMD used:
MFTECmd.exe -f "D:\NTFS\$MFT" --csv D:\SANDBOX\NTFS\EXPORT

As for why here, your Documentation page has "Any feedback, suggestions, errors, etc can be reported [here]", it's not super obvious that it's meant only for docs, sorry for that.

**Comment by EricZimmerman** [comment]
How did you extract the mft tho? 

Can you try -f 'd:\$mft' and let it read it live? Enable debug as well and it will tell you what file record it's on. May be it's corrupt

**Comment by EricZimmerman** [comment]
Based on the error it looks like it's running out of data.

**Comment by 0CM** [comment]
Originally I exported the $MFT from FTK Imager.

This time I mounted the image via AIM v3.11.279.

Parsing failed the same way, attaching the debug log.
[MFTECmd_debug.txt](https://github.com/EZToolsManuals/EZToolsManuals/files/14655145/MFTECmd_debug.txt)

**Comment by 0CM** [comment]
Here is the 1024 bytes from the 0x194B800 offset.
[0x194B800dmp.txt](https://github.com/EZToolsManuals/EZToolsManuals/files/14656365/0x194B800dmp.txt)

**Comment by EricZimmerman** [comment]
this is less than helpful. id need the bytes only, not a text representation of them =(

i converted it, but it was a pain. you can use MFTECmd to extract out file records.

this looks like a corrupt record. is there anything after it?


if you wanna zip the whole mft and share that i can take a look as well.

**Comment by 0CM** [comment]
Yes, there are more file records.

0194bc00: 4649 4c45 3000 0300 b7c3 6f47 0000 0000  FILE0.....oG...

Here is the MFT

[MFT.zip](https://github.com/EZToolsManuals/EZToolsManuals/files/14656773/MFT.zip)


Thank you

**Comment by 0CM** [comment]
Hi Eric , that's briliant, thank you very much for fixing this and for your patience with me.

Have a good day.
